name: reach_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_lints: ^2.0.1
  flutter_mobx: ^2.0.6+5
  flutter_modular: ^5.0.3
  mobx: ^2.1.3+1
  crypto:

dev_dependencies:
  dart_code_metrics: ^5.6.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - .env 
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700